#!/bin/bash


DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
path=$DIR'/coletas/'
mkdir -p $path
export path
sudo service seedd stop
fname="$( date +"%Y%m%dT%H%M%S" )"
number=1

while ( true ); do
	before=`date +%s%3N`
	sudo seedd -i JA1ANI --limit-max-xfer --no-qa -f0 -b 256 | xxd -b -c256 | cut -f 2-257 -d ' ' | sed 's/[^1]//g' | awk -v num="$number" -v date="$(date +"%T")" '{ print num, length, date }' >>$path$fname-w.txt; awk -v num="$number" -v date="$(date +"%T")" -F ' ' '{s+=$2;sum+=$2;a[NR]=$2} END {print date, (s/NR-1024)/((22.627417)/sqrt(NR))}' $path$fname-w.txt >> $path$fname'zscore-w.txt' 2>/dev/null & sudo seedd -i OSYJHX --limit-max-xfer --no-qa -f1 -b 256 | xxd -b -c256 | cut -f 2-257 -d ' ' | sed 's/[^1]//g' | awk -v num="$number" -v date="$(date +"%T")" '{ print num, length, date }' >>$path$fname-b.txt; awk -v num="$number" -v date="$(date +"%T")" -F ' ' '{s+=$2;sum+=$2;a[NR]=$2} END {print date, (s/NR-1024)/((22.627417)/sqrt(NR))}' $path$fname-b.txt >> $path$fname'zscore-b.txt' 2>/dev/null 
	number=$(( ++number ))
	after=`date +%s%3N`
	DELAY=`echo "1-(($after-$before)/1000)" | bc -l`
	sleep $DELAY 2>/dev/null
done &
echo -e "\e[1;36;5mCollecting data...\e[0m"
read -p "Press [Enter] key to stop..."
sudo ps -ef | awk '/bduoplot/{print$2}' | xargs kill 2>/dev/null



